---
title: "Lobster Exploration"
author: "Peter Menzies"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

## Read in lobster data

```{r}
lobsters <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", " ")) %>% 
  clean_names() %>% 
  uncount(count) 

# uncount() is turning frequency data (within the column "count") into separate observations (rows)

```

### Find the total counts and mean carapace length by site and year

```{r}
count_carapace <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(total_counts = n(), mean_carapace_length = mean(size_mm, na.rm = TRUE))
```

### Plotting our summary

```{r}
lobsters_plot <- ggplot(count_carapace, aes(x = year, y = total_counts)) +
  geom_line(aes(color = site))

lobsters_plot
```

### Create a subset that only contains obs from 2020

```{r}
lobsters_2020 <- lobsters %>% 
  filter(year == 2020)

# check for values in year column
unique(lobsters_2020$year)

# add a column denoting legality based on size

lobsters_2020 <- lobsters_2020 %>% 
  mutate(legal = case_when(
    size_mm >= 79.76 ~ "legal",
    size_mm < 79.76 ~ "illegal"
  ))

legal_lobsters <- lobsters_2020 %>% 
  filter(legal == "legal")

site_counts <- lobsters_2020 %>% 
  group_by(site, legal) %>% 
  summarize(count = n())

# alternatively we could use the count() finction given the arguments "site" and "legal" - same output as what we did above
```

### Create a stacked column graph of legal and illegal at each site

```{r}
counts_2020_plot <- ggplot(site_counts, aes(x = site, y = count)) +
  geom_col(position = "fill", aes(color = legal, fill = legal))

counts_2020_plot
```

## Data wrangling yeeeehaaaawww

Filter practice

```{r}
ex_1 <- lobsters %>% 
  filter(site %in% c("IVEE", "NAPL", "CARP"))

#check if our filter worked:
unique(ex_1$site)

ex_2 <- lobsters %>% 
  filter(month == 8)

ex_3 <- lobsters %>% 
  filter(site == "AQUE" | size_mm > 70)

ex_4 <- lobsters %>% 
  filter(site != "NAPL")
```

group_by(), summarize() practice

```{r}
ex_e <- lobsters %>% 
  group_by(site) %>% 
  summarize("mean_length" = mean(size_mm, na.rm = TRUE),
            "sd_length" = sd(size_mm, na.rm = TRUE))

ex_f <- lobsters %>% 
  group_by(site, month) %>% 
  summarize("max_length" = max(size_mm, na.rm = TRUE))
```

mutate() practice

```{r}
ex_g <- lobsters %>% 
  mutate(size_cm = size_mm / 10)

ex_h <- lobsters %>% 
  mutate(site = tolower(site))
# ^^ make lower case function

ex_i <- lobsters %>% 
  mutate(area = as.character(area))
```

case_when() practice

```{r}
ex_j <- lobsters %>% 
  mutate(size_bin = case_when(
    size_mm <= 70 ~ "small",
    size_mm > 70 ~ "large"
  ))

ex_k <- lobsters %>% 
  mutate(designation = case_when(
    site == "IVEE" | site == "NAPL" ~ "MPA",
    !site %in% c("IVEE", "NAPL") ~ "not MPA" 
  ))
```

